//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DESCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public int Id { get; set; }
        public string DeviceId { get; set; }
        public string PhoneNumber { get; set; }
        public string IpAddress { get; set; }
        public string ACMVersion { get; set; }
        public long InBound { get; set; }
        public long OutBound { get; set; }
        public bool IsConnect { get; set; }
        public System.DateTime DateUpdated { get; set; }
    }
}
