//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DESCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resident
    {
        public int Id { get; set; }
        public int SiteId { get; set; }
        public int FlatNumber { get; set; }
        public string ResidentName { get; set; }
        public string HomeTel { get; set; }
        public string MobileTel { get; set; }
        public string Email { get; set; }
        public int TagIndex { get; set; }
        public System.DateTime DateUpdated { get; set; }
    }
}
