//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DESCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int Id { get; set; }
        public int SiteDataId { get; set; }
        public int ScheduleIndex { get; set; }
        public int Start1Hour { get; set; }
        public int Start1Minute { get; set; }
        public int End1Hour { get; set; }
        public int End1Minute { get; set; }
        public int Day1 { get; set; }
        public int Start2Hour { get; set; }
        public int Start2Minute { get; set; }
        public int End2Hour { get; set; }
        public int End2Minute { get; set; }
        public int Day2 { get; set; }
        public System.DateTime DateUpdated { get; set; }
    }
}
