//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DESCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int Id { get; set; }
        public int CheckPeriod { get; set; }
        public int MaxDataSize { get; set; }
        public int MaxEventlogSize { get; set; }
        public System.DateTime DateReset { get; set; }
        public int ReservedChannel { get; set; }
        public System.DateTime DateUpdated { get; set; }
    }
}
