//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DESCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffGroup
    {
        public int Id { get; set; }
        public string StaffGroupName { get; set; }
        public int StaffId1 { get; set; }
        public int StaffId2 { get; set; }
        public int StaffId3 { get; set; }
        public int StaffId4 { get; set; }
        public int StaffId5 { get; set; }
        public int StaffId6 { get; set; }
        public int StaffId7 { get; set; }
        public int StaffId8 { get; set; }
        public int Tag1 { get; set; }
        public int Tag2 { get; set; }
        public int Tag3 { get; set; }
        public int Tag4 { get; set; }
        public int Tag5 { get; set; }
        public int Tag6 { get; set; }
        public int Tag7 { get; set; }
        public int Tag8 { get; set; }
        public long Door1 { get; set; }
        public long Door2 { get; set; }
        public System.DateTime DateUpdated { get; set; }
    }
}
