//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DESCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffGroupSite
    {
        public int Id { get; set; }
        public int StaffGroupId { get; set; }
        public int SiteId { get; set; }
        public int ChannelIndex { get; set; }
        public System.DateTime DateUpdated { get; set; }
    }
}
