//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DESCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemOption
    {
        public int Id { get; set; }
        public int SiteDataId { get; set; }
        public int Option1 { get; set; }
        public int Option2 { get; set; }
        public int TradeSchedule { get; set; }
        public int RingTimeout { get; set; }
        public int AudioTimeout { get; set; }
        public int WardenChannel { get; set; }
        public int CustomerNo { get; set; }
        public int SiteNo { get; set; }
        public System.DateTime DateUpdated { get; set; }
    }
}
