//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DESCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Sites = new HashSet<Site>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string DefaultPassword { get; set; }
        public string Password { get; set; }
        public int UserTypeId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string ContactNumber { get; set; }
        public bool IsLogin { get; set; }
        public string ViewP { get; set; }
        public string EditP { get; set; }
        public string ReadP { get; set; }
        public string WriteP { get; set; }
        public System.DateTime DateUpdated { get; set; }
    
        public virtual ICollection<Site> Sites { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
